### PR TITLE
[5.4] implement `size()` method

### PR DESCRIPTION
**Pull request by AaronJan**

### CODE REVIEW

**Comment by AaronJan** [comment]
.. What is the Scrutinizer test?

**Comment by vladimir-yuldashev** [comment]
@AaronJan Hello, Travis seems to fail. Can you fix it, please?

**Comment by AaronJan** [comment]
I fixed Travis, but there is nothing I can do about Scrutinizer..

**Comment by vladimir-yuldashev** [comment]
Ignore Scrutinizer, I need to turn it off.

Great job, thanks!

**Pull request merged**
