### PR TITLE
Fixed #49

### LINKED ISSUE #49: Use php-amqplib/php-amqplib instead of videlalvaro/php-amqplib
As the latter one is officially abandoned (and marked as such in packagist) the _new_ maintained version **php-amqplib/php-amqplib** should be used instead.

### PR DESCRIPTION
**Pull request by sebwas**

### CODE REVIEW

**Comment by fusion52** [comment]
Issue most likely on my composer config. Any recommendations?  I added to the composer.json:
`
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/sebwas/laravel-queue-rabbitmq"
    }
],
"require": {
    "sebwas/laravel-queue-rabbitmq": "master"
}
`
Results.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package sebwas/laravel-queue-rabbitmq could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by sebwas** [comment]
Yeah, that's due to my package not being on packagist. I can put it there
until the PR is processed. Just give me 10 minutes and try again.

**Comment by sebwas** [comment]
Or no. I have an even better idea. In your composer.json file, put it like

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/sebwas/laravel-queue-rabbitmq"
        }
    ],
    "require": {
        "vladimir-yuldashev/laravel-queue-rabbitmq": "dev-issue-49"
    }
}
```

Alternatively you could use

```
...
    "require": {
        "sebwas/laravel-queue-rabbitmq": "dev-master"
    }
...
```

But I suggest you use the other one.

**Comment by fusion52** [comment]
That did the trick.  Thank you.

**Comment by ramilexe** [comment]
@sebwas your way

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/sebwas/laravel-queue-rabbitmq"
        }
    ],
    "require": {
        "vladimir-yuldashev/laravel-queue-rabbitmq": "dev-issue-49"
    }
}
```
doesn't work for me.

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package vladimir-yuldashev/laravel-queue-rabbitmq could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by sebwas** [comment]
The problem is that you'll have to use `"minimum-stability": "dev"` in your composer.json. Otherwise it will only fetch stable versions with a version number which is not the case here.

**Pull request closed without merging**
